module.exports = {
  github: {
    fullName: "h1.vcard-names span.p-name",
    bio: "div.p-note div",
    location: "span.p-label",
    company: "",
    website: "li[itemprop='url'] a",
    followers: "a[href$='followers'] span",
    following: "a[href$='following'] span",
    repos: "a[href$='repositories'] span",
    stars: "a[href$='stars'] span",
    gists: "a[href$='gists'] span",
    email: "li[itemprop='email']",
    twitter: "li[itemprop='social']",
    linkedin: "li[itemprop='linkedin']",
    facebook: "li[itemprop='facebook']",
    blog: "li[itemprop='blog']",
    hireable: "li[itemprop='hireable']",
    created: "li[itemprop='created']",
    updated: "li[itemprop='updated']",
    lastActive: "li[itemprop='lastActive']",
    bioLink: "div.p-note a",
    bioLinkText: "div.p-note a span",
  },
  linkedin: {
    fullName: "h1.top-card-layout__title",
    position: "h2.top-card-layout__headline",
    location: "span.top-card__subline",
    company: "h3.top-card__flavor",
    website: "a.top-card__link",
    followers: "span.top-card__followers",
    following: "span.top-card__following",
    connections: "span.top-card__connections",
    posts: "a[data-control-name='view_all_posts'] span",
    articles: "a[data-control-name='view_all_articles'] span",
    videos: "a[data-control-name='view_all_videos'] span",
    endorsements: "a[data-control-name='view_all_endorsements'] span",
    recommendations: "a[data-control-name='view_all_recommendations'] span",
    skills: "span.pill__text",
    endorsementsCount: "span.pill__count",
    email: "a[data-control-name='contact_see_more']",
    twitter: "a[data-control-name='twitter']",
    blog: "a[data-control-name='blog']",
    hireable: "span.pill__text",
    created: "span.pill__text",
    updated: "span.pill__text",
    lastActive: "span.pill__text",
    bioLink: "a[data-control-name='bio_link']",
    bioLinkText: "a[data-control-name='bio_link'] span",
  },
  facebook: {
    fullName: "h1._64-f",
    bio: "div._5pbx.userContent",
    location: "div._5v-0",
    company: "div._5v-0",
    website: "a._5v-0",
    followers: "a[href$='followers'] span",
    following: "a[href$='following'] span",
    friends: "a[href$='friends'] span",
    posts: "a[href$='posts'] span",
    photos: "a[href$='photos'] span",
    videos: "a[href$='videos'] span",
    groups: "a[href$='groups'] span",
    events: "a[href$='events'] span",
    email: "li[itemprop='email']",
    twitter: "li[itemprop='twitter']",
    blog: "li[itemprop='blog']",
    hireable: "li[itemprop='hireable']",
    created: "li[itemprop='created']",
    updated: "li[itemprop='updated']",
    lastActive: "li[itemprop='lastActive']",
    bioLink: "div._5pbx a",
    bioLinkText: "div._5pbx a span",
  },
};
